#!/usr/bin/env bash
# QUICK SETUP: Set Vercel Environment Variables for HVAC Chatbot
# Run this after getting your OpenAI API key from https://platform.openai.com/api-keys

echo "🚀 HVAC Chatbot - Vercel Environment Setup"
echo "==========================================="
echo ""
echo "Step 1: Make sure you're logged into Vercel:"
echo "  $ vercel login"
echo ""
echo "Step 2: Get your OpenAI API key:"
echo "  👉 https://platform.openai.com/api-keys"
echo ""
echo "Step 3: Run these commands (replace YOUR_KEY_HERE with your actual key):"
echo ""
echo "  echo 'sk-proj-YOUR_KEY_HERE' | vercel env add OPENAI_API_KEY --environment=production"
echo "  echo 'gpt-4o-mini' | vercel env add OPENAI_MODEL --environment=production"
echo "  echo '7000' | vercel env add OPENAI_TIMEOUT_MS --environment=production"
echo "  echo '320' | vercel env add OPENAI_MAX_TOKENS --environment=production"
echo "  echo '8' | vercel env add OPENAI_HISTORY_MAX_TURNS --environment=production"
echo ""
echo "Step 4: Verify variables are set:"
echo "  $ vercel env ls"
echo ""
echo "Step 5: Redeploy to production:"
echo "  $ vercel deploy --prod"
echo ""
echo "Step 6: Test the chatbot:"
echo "  👉 https://potter-perrone.vercel.app"
echo ""
echo "✅ The chatbot should now give real AI responses!"
echo ""
echo "---"
echo "📖 For detailed setup guide, see: docs/VERCEL-ENV-SETUP.md"
echo "🐛 For troubleshooting: https://github.com/Custom-Coding-Creations/hvac/issues"
